### ISSUE TITLE
[FEAT] 긴급알림 PushNotification 구현

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#106]
## 💡 Issue

- 긴급알림 PushNotification 구현
## 📝  todo

- [ ] cloud Messaging 세팅
- [ ] remote Notification 구현
- [ ] Token 데이터 서버 및 데이터구조 일부 수정

**Comment by monic98** [comment]
@KimDaeSeong8721 UX writing은 이렇게 해주시면 될 듯 합니다!

<img width="415" alt="스크린샷 2022-08-24 오후 6 13 03" src="https://user-images.githubusercontent.com/103012323/186379783-55b04efe-191a-4c90-bdff-db7bab62c9cd.png">

**Comment by KimDaeSeong8721** [comment]
> @KimDaeSeong8721 UX writing은 이렇게 해주시면 될 듯 합니다!
> 
> <img alt="스크린샷 2022-08-24 오후 6 13 03" width="415" src="https://user-images.githubusercontent.com/103012323/186379783-55b04efe-191a-4c90-bdff-db7bab62c9cd.png">

n개의 알림을 반영하는게 기술적으로 많은 기술적 노력(파이어베이스랑 다른 서버 언어 연결필요)이 필요해서 힘들거 같아요ㅜㅜ.
특정 시간마다 알림을 확인해주세요라는 방식으로 가야될 거같아요. 이게 UX 측면에서 많이 어색하다고 생각하시면 이 부분에 대해 논의를 해봐야 할 거 같아요
