### ISSUE TITLE
[ADD] 캘린더뷰 코드 리펙터링 (단순정리)

### ISSUE THREAD

**Issue by heokyeol** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#108]
## 💡 Issue

복잡한 캘린더뷰의 코드와 필수 해결 에러를 수정한다.

## 📝  todo

- [x] 동일한 함수 정리하기(교사와 학부모뷰에서 동일한)
- [ ] 날자 수동 수정 이슈 해결하기
- [ ] 코드 정리하기 (가독성 등등)
