### ISSUE TITLE
[CHORE] 학부모 뷰 세부 UI 조정

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#44]
## 💡 Issue
- 예약내역 테이블뷰 상세 수정
- 긴급상담 신청 기능 noti 연결
- 쪽지 건의화면 상세 수정

## 📝  todo
 [예약내역]
- [x] table cell layout, height
- [ ] button indicator
- [x] detail information view

 [긴급상담]
- [x] submit -> noti mockdata
- [x] text field limit

 [메세지 전송]
- [x] date formatter
- [x] send button pop-up layout
- [x] time difference error
