### ISSUE TITLE
[FEAT] 파이어베이스 가져오기 함수 구현

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#52]
## 💡 Issue

- [FEAT] 파이어베이스 가져오기 함수 구현
## 📝  todo

- [x]  학부모 여러명의 예약정보들 가져오기 for 선생님
- [x]  학부모 1명의 예약정보 가져오기 for 학부모
- [x]  학부모 여러명의 메시지들 가져오기 for 선생님
- [x]  학부모 1명의 메시지들 가져오기 for 학부모
- [x]  알림들 가져오기 for 선생님
