### ISSUE TITLE
[FEAT] 파이어베이스 메시지 연결 

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#69]
## 💡 Issue

- 파이어 베이스 메시지 연결 for 학부모
- 파이어 베이스 메시지 연결 for 선생님

<p align="left">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/69894461/182029387-5036fe18-5cab-4280-ac87-d71152009093.png"> |
<img width="270" alt="image" src="https://user-images.githubusercontent.com/69894461/182029428-6fb5bbea-96a6-437f-8792-fd1a8e0547e8.png">
</p>
## 📝  todo

- [x] 파이어베이스 메시지 연결 for 학부모
- [x] 파이어베이스 메시지 연결 for 선생님
- [x] 처리완료 버튼 로직 함수 구현 및 적용
