### ISSUE TITLE
[ADD] 긴급상담 토스트 메시지

### ISSUE THREAD

**Issue by hardworking-nomad** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#78]
## 💡 Issue
- 공용 컴포넌트 활용하여 View 하이파이로 버전으로 업데이트
<img width="251" alt="image" src="https://user-images.githubusercontent.com/103012800/182288183-eca0cca5-26bd-4b1b-80e8-fa34fb48c68b.png">

- 토스트 메시지 구현
<img width="232" alt="image" src="https://user-images.githubusercontent.com/103012800/182288671-80993ece-d8ba-4c33-8807-ac2d469327cd.png">

## 📝  todo
- [x] Status Indicator 를 secondary button으로 교체
- [ ] 예약내역 보는 테이블뷰에서 하나의 예약 클릭 후 다른 뷰 클릭 시 빠져나오기 구현 (resign firstresponder)
- [x] Custom Nav Bar 일괄 적용
- [ ] 쪽지 전송 시 Date Picker의 색과 다른 셀의 색상 동일하게 수정
- [x] 뷰마다 백그라운드 색상 일괄 수정
- [ ] 긴급상담 토스트 메시지 구현
