### ISSUE TITLE
[CHORE] 전체적인 디자인 수정 등 for 선생님

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#85]
## 💡 Issue

- 전체적인 디자인 수정
- 앱아이콘 추가
- 파베 코드 일부 수정
## 📝  todo

- [x] firebase- asyncafter 수정
- [x] 앱아이콘 추가
- [x] 커스텀네비게이션바 타이틀 사이즈 인자 추가
- [x] 선생님 뷰들 backgroundColor 수정
- [x] 탭바 backgroundColor 수정
- [x] 선생님 전화상담 뷰에 커스텀네비게이션바 추가
